name: test_docker

on:
  push:
    branches: [ "master" ]
    
jobs:
  # Enforces the update of a changelog file on every pull request.
  test1:
    runs-on: ubuntu-latest
    steps:
      # checks for updates to CHANGELOG.md
      # https://github.com/marketplace/actions/changelog-enforcer
      - uses: cloudera/ml-runtimes@public-runtimes

      - name: test
        run: |
          ls
          pwd
