name: test_docker

on:
  push:
    branches: [ "master" ]
    
jobs:
  # Enforces the update of a changelog file on every pull request.
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout cloudera cml
        uses: actions/checkout@public-runtimes
        with:
          repository: cloudera/ml-runtimes

      - name: test files
        run: |
          ls
          pwd
