name: test_docker

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: test docker
      run:  |
            docker build -f 'https://github.com/cloudera/ml-runtimes/blob/public-runtimes/pbj-workbench-python3.8-cuda.Dockerfile' --target my-target --label my-label .


