name: test_docker

on:
  push:
    branches: [ "master" ]
    
jobs:
  # Enforces the update of a changelog file on every pull request.
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout cloudera cml
        uses: actions/checkout@master
        with:
          repository: cloudera/ml-runtimes

      - name: test files
        run: docker build -t cml_3.9 -f "pbj-workbench-python3.9-standard.Dockerfile" .

      - name: image ls
        run: docker image ls

      - name:  ls
        run: ls
          
          
