name: test_docker

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check
      run:   ls
    - name: clone runtimes
      run:   git clone https://github.com/cloudera/ml-runtimes.git
    - name: buid cml_3.9
      run: |  
            ls
            cd ml-runtimes
            docker build -t cml_3.9 -f "pbj-workbench-python3.9-standard.Dockerfile" .

    - name: create container
      run:  docker run v /.:/. --name test1 cml_3.9 

    - name: check folders
      run:  ls 

    - name: check python version
      run: docker exec test1 ls -lsa

    - name: check folders2
      run:  ls 

