name: test_docker

on:
  push:
    branches: [ "master" ]
    
jobs:
  # Enforces the update of a changelog file on every pull request.
  build_cml:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout cloudera cml
        uses: actions/checkout@master
        with:
          repository: cloudera/ml-runtimes

      - name: build
        run: docker build -t cml_3.9 -f "pbj-workbench-python3.9-standard.Dockerfile" .
      - name: ls in cml
        run: |
          ls
          docker image ls

      - name: checkout root
        uses: actions/checkout@v3

      - name: run
        run:  docker run -id --name test1 cml_3.9 
      - name: test1
        run:  docker cp $(pwd)/. cml_3.9:/
      - name: test2
        run:  docker exec cml_3.9 ls -la /

        

