name: test_docker

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: test docker
      run:  |
            docker pull cloudera/ml-runtime-workbench-python3.9-standard-rsync
            docker image ls


             
