name: test_docker

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: test docker
      run:  |
             git clone https://github.com/cloudera/ml-runtimes.git
             cd ml-runtimes
             ls
             echo "$PWD"
             docker build -f pbj-workbench-python3.8-cuda.Dockerfile --target my-target --label my-label .
             docker image ls
