name: test_docker

on:
  push:
    branches: [ "master" ]
    
jobs:
  # Enforces the update of a changelog file on every pull request.
  build_cml:
    runs-on: ubuntu-latest
    steps:
      - name: checkout cloudera cml
        uses: actions/checkout@master
        with:
          repository: cloudera/ml-runtimes

      - name: build
        run: docker build -t cml_3.9 -f "pbj-workbench-python3.9-standard.Dockerfile" .

      - name: image ls
        run: docker image ls

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: cml_3.9:latest
          outputs: type=docker,dest=/tmp/myimage.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myimage
          path: /tmp/myimage.tar

  use:
    runs-on: ubuntu-latest
    needs: build_cml
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: myimage
          path: /tmp
      
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a          


 
