# Action name
name: test_cml_ci

# Here, this action will be enabled on all pushes.
# Modify this to fit your needs.
on:
    push

# Jobs section
jobs:
    # The job that will use the container image you just pushed to ghcr.io
    super-job:
        runs-on: ubuntu-latest
        container:
            image: https://github.com/cloudera/ml-runtimes/blob/public-runtimes/pbj-workbench-python3.10-cuda.Dockerfilel:latest 
        steps:
            - name: test_echo
              shell: bash
              run: |
                echo "Oh yeah"
