name: test_docker

on:
  push:
    branches: [ "master" ]
    
jobs:
  # Enforces the update of a changelog file on every pull request.
  build_cml:
    runs-on: ubuntu-latest
    steps:
      - name: checkout cloudera cml
        uses: actions/checkout@master
        with:
          repository: cloudera/ml-runtimes

      - name: build
        run: docker build -t cml_3.9 -f "pbj-workbench-python3.9-standard.Dockerfile" .

      - name: image ls
        run: docker image ls

  test2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check
      run:   ls
    - name: image ls
      run: docker image ls

 
